In [1]:
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler 
import pandas as pd 
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt
import time
import sys
%matplotlib inline
import random
import copy
import logging
from tqdm import tqdm
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
import keras.backend as K
import tensorflow as tf
from tsfresh import extract_features
import tsfresh.feature_extraction.feature_calculators as features
from pandas import DataFrame
import FFNN_Function
import LSTM_Function

# Setup logging.
logger = logging.getLogger()
fhandler = logging.FileHandler(filename='meta-learning.log', mode='a')
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fhandler.setFormatter(formatter)
logger.addHandler(fhandler)
logger.setLevel(logging.DEBUG)

Serie_names = ['Serie 1','Serie 2','Serie 3','Serie 4','Serie 5','Serie 6','Serie 7','Serie 8','Serie 9','Serie 10','Serie 11','Serie 12']
tree_examples = DataFrame (columns  = ['FFNN','ARIMA','LSTM','length','kurtosis','energy','variance'], index = Serie_names)

Using TensorFlow backend.

In [2]:
Series = pd.read_excel("NN3_FINAL_DATASET_WITH_TEST_DATA.xlsx", sheet_name="Hoja 1")
Series

,Serie 1,Serie 2,Serie 3,Serie 4,Serie 5,Serie 6,Serie 7,Serie 8,Serie 9,Serie 10,Serie 11,Serie 12,Unnamed: 12
0,4998,5033.0,5304,685.0,5006.9,4950,4318,1740.0,6318.0,2605,3140,4207.354924,1
1,4480,4509.5,4264,656.0,5165.1,4900,4224,1005.0,5991.0,2510,3270,4546.487134,2
2,4824,3970.0,3224,1288.0,4975.5,5500,4014,1792.5,6405.0,3520,3690,705.600040,3
3,4814,3378.0,2400,3914.0,4983.6,5550,3620,1965.0,6230.0,3200,4360,-3784.012477,4
4,4602,2866.0,1968,6837.0,5105.4,5900,3512,2085.0,6111.0,2550,3520,-4794.621373,5
5,4499,2315.5,1532,7104.0,5025.5,5150,3590,2440.0,5317.0,2640,4140,-1397.077491,6
6,4594,1895.0,1000,7464.0,4847.8,5700,3700,2317.5,4893.0,2280,3440,3284.932994,7
7,4600,8401.5,55024,6308.0,4963.3,6450,3752,2312.5,4867.0,2620,3750,4946.791233,8
8,4507,8040.0,53804,5549.0,4796.0,4800,3866,2667.5,4785.0,1940,4140,2060.592426,9
9,4606,7534.0,42540,6365.0,5042.0,6300,3892,3655.0,5099.0,1415,5610,-2720.105554,10
10,4503,7135.5,26572,6344.0,5027.8,5700,3838,2245.0,5142.0,1775,5350,-4999.951033,11
11,4801,6466.5,15748,5597.0,4668.3,4900,3936,3000.0,5335.0,2320,4270,-2682.864590,12
12,4564,5661.5,10372,1178.0,4646.2,4900,4200,2795.0,5450.0,2585,3160,2100.835184,13
13,4142,4896.0,8980,1581.0,4912.4,5500,4184,3492.5,5161.0,2885,2560,4953.036778,14
14,4818,4064.5,7212,1870.0,5040.5,5550,3708,3097.5,5516.0,2870,3410,3251.439201,15
15,4408,3296.0,7504,5230.0,5100.9,5200,3708,3665.0,4850.0,3010,3670,-1439.516583,16
16,4496,2593.5,3848,8046.0,5143.3,5500,3760,6555.0,4250.0,2710,3670,-4806.987459,17
17,4587,2007.0,2684,7997.0,4998.2,4950,3708,3040.0,4451.0,3070,3200,-3754.936234,18
18,4656,1513.5,1000,9216.0,5053.2,5900,3846,8877.5,5442.0,2050,3700,749.386048,19
19,4799,6645.0,43560,8077.0,5024.4,5700,3748,3280.0,5426.0,2315,3430,4564.726254,20
20,4652,6221.5,40320,6021.0,5298.8,5300,3836,3202.5,5329.0,2140,4130,4183.278193,21
21,4638,5474.0,28096,6399.0,4946.7,5550,3790,4592.5,5150.0,1950,4870,-44.256546,22
22,4650,5135.5,17804,6857.0,4871.8,4600,3968,2600.0,5030.0,3150,6310,-4231.102021,23
23,5185,4630.5,10008,3446.0,4563.4,5650,3756,4802.5,4833.0,4510,4680,-4527.891810,24
24,5208,4164.0,6136,1544.0,4580.1,4950,3760,3685.0,4437.0,3685,2380,-661.758751,25
25,4477,3600.5,4216,2031.0,4909.2,4850,3986,3687.5,4334.0,5125,3430,3812.792252,26
26,4976,2969.0,2424,2561.0,5002.2,5050,4096,2615.0,4165.0,5750,2950,4781.879642,27
27,4670,2503.5,1840,5166.0,5126.9,5500,4194,3070.0,3704.0,4580,3130,1354.528942,28
28,4842,2054.5,1112,7470.0,5060.4,5300,4254,2597.5,3616.0,4555,3650,-3318.169421,29
29,4713,1608.5,324,6849.0,4946.7,5250,4130,2617.5,3476.0,3430,2980,-4940.158120,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,5261,2861.5,1200,7158.0,4477.4,5400,3466,2537.5,3527.0,2000,2800,4727.176670,115
115,5327,9486.5,55896,6658.0,4367.5,5750,3468,3437.5,3336.0,1975,3220,1183.306967,116
116,5054,9061.0,49948,6423.0,4395.6,5100,3586,3557.5,3320.0,1475,3120,-3448.489705,117
117,5269,8877.5,35900,6351.0,4528.1,4550,3366,4387.5,3599.0,1730,4000,-4909.760845,118
118,5019,8557.5,19352,5735.0,4554.3,4650,3500,1950.0,3301.0,2900,4840,-1857.020507,119
119,5315,8031.0,7828,5820.0,4316.2,5000,3666,2817.5,3195.0,3405,2630,2903.055921,120
120,5274,7404.5,4324,2966.0,4481.7,4350,3858,2422.5,3354.0,3130,2920,4994.076124,121
121,4899,6852.5,4104,2089.0,4719.0,4250,3842,3537.5,3025.0,3490,2350,2493.565769,122
122,5216,6174.5,3972,2892.0,4854.7,5200,3668,4465.0,3369.0,3675,2850,-2299.517453,123
123,5029,5341.5,2828,5992.0,4819.5,4600,3700,4835.0,3357.0,2705,2700,-4978.434934,124
124,5110,4975.5,4304,6718.0,4704.1,4800,3748,2595.0,3501.0,2440,2870,-3080.202296,125
125,5093,4290.0,4876,9275.0,4607.9,5100,3790,3910.0,3331.0,2615,2580,1649.954128,126
126,5314,3492.5,1800,7163.0,4544.3,4950,3640,5637.5,3275.0,1515,2450,4863.150336,127
127,5248,8691.0,47228,6915.0,4450.8,5400,3364,3672.5,3397.0,1245,2950,3605.188553,128
128,5063,8097.5,44588,6919.0,4348.6,5150,3400,3870.0,3276.0,1245,3350,-967.366960,129
129,5409,7578.5,28908,5870.0,4410.3,5250,3374,5747.5,3450.0,1120,4450,-4650.529751,130
130,5127,6958.5,11260,6316.0,4563.8,5200,3564,3362.5,3351.0,1895,4210,-4058.016936,131
131,5558,6401.5,5828,6036.0,4405.8,4700,3582,4505.0,3139.0,3160,2650,265.417936,132
132,5116,5644.5,4416,3021.0,4520.8,5150,3940,4520.0,3031.0,2240,2414,4344.828781,133
133,4922,4947.0,4612,NaN,4857.9,4600,4034,4887.5,2566.0,3420,2823,4429.624082,134
134,5503,4016.5,3084,NaN,4972.6,4950,3776,NaN,2985.0,3095,2444,441.843431,135
135,5039,3487.5,3372,NaN,4894.7,4700,3694,NaN,2675.0,3050,2666,-3952.166034,136
136,5116,2889.0,3516,NaN,4814.5,5150,3742,NaN,2710.0,3360,3052,-4712.572273,137
137,5109,2168.5,1940,NaN,4621.5,5100,3700,NaN,2690.0,1165,2397,-1140.261298,138
138,5334,1614.0,1476,NaN,4529.7,5300,3550,NaN,2929.0,4250,2463,3480.400656,139
139,5324,7987.0,54960,NaN,4540.7,5600,3338,NaN,2916.0,2400,3385,4901.198297,140
140,5313,7257.0,46128,NaN,4432.7,5000,3428,NaN,2932.0,2330,3290,1815.856827,141
141,5341,6927.5,28840,NaN,4506.9,5350,3510,NaN,NaN,2475,5408,-2938.975036,142
142,5306,6586.5,14916,NaN,4664.6,4800,3652,NaN,NaN,2480,4000,-4991.726804,143
143,5545,5989.0,6088,NaN,4591.4,4650,3750,NaN,NaN,3250,2513,-2455.107969,144

In [9]:
steps_ahead = 1
test_size = 14

logging.info("Empezando proceso de llenado de tabla")

for i in Serie_names:
    logging.info("Empieza la serie %s ", i)
    Serie = Series[i].astype(float)
    Serie = Serie.dropna()
    Serie = Serie.values
    Serie = Serie.reshape(Serie.shape[0],-1)
    scaler = MinMaxScaler(feature_range = (0.1, 0.9))
    Serie = scaler.fit_transform(Serie)  
    Serie_flat = Serie.ravel()
    energy = features.abs_energy(Serie_flat)
    length = features.length(Serie_flat)
    kurtosis = features.kurtosis(Serie_flat)
    variance = features.variance(Serie_flat)
    tree_examples.loc[i][['length','kurtosis','energy','variance']] = [length, kurtosis, energy, variance]
    
    
    logging.info("Empieza proceso genetico con FFNN")
    try:
        FFNN = FFNN_Function.main(steps_ahead,test_size,Serie,i)[0].mse
    except Exception as e:
        FFNN = -1
        logging.error("Exception occurred", exc_info=True)

    tree_examples.loc[i]['FFNN'] = FFNN
    tree_examples.to_csv(r'C:\Users\hug0er\Documents\Tesis\Meta-Table.csv')
    
    
    
    logging.info("Empieza proceso genetico con LSTM")
    try:
        LSTM = LSTM_Function.main(steps_ahead,test_size,Serie,i)[0].mse
    except Exception as e:
        LSTM = -1
        logging.error("Exception occurred", exc_info=True)

    tree_examples.loc[i]['LSTM'] = LSTM
    tree_examples.to_csv(r'C:\Users\hug0er\Documents\Tesis\Meta-Table.csv')
    
    
    
    logging.info("Empieza proceso de auto-ARIMA")
    try:
        ARIMA = ARIMA_Function.main(steps_ahead,test_size,Serie,i)[0].mse
    except Exception as e:
        ARIMA = -1
        logging.error("Exception occurred", exc_info=True)

    tree_examples.loc[i]['ARIMA'] = ARIMA
    tree_examples.to_csv(r'C:\Users\hug0er\Documents\Tesis\Meta-Table.csv')
    
tree_examples

  0%|          | 0/10 [00:00<?, ?it/s]

(122, 8)
(122, 8)
(122, 8, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(124, 6)
(124, 6)
(124, 6, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(126, 4)
(126, 4)
(126, 4, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(115, 4)
(115, 4)
(115, 4, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(124, 6)
(124, 6)
(124, 6, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(124, 6)
(124, 6)
(124, 6, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(122, 8)
(122, 8)
(122, 8, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(108, 12)
(108, 12)
(108, 12, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(121, 6)
(121, 6)
(121, 6, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(122, 8)
(122, 8)
(122, 8, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(124, 6)
(124, 6)
(124, 6, 1)

  0%|          | 0/10 [00:00<?, ?it/s]

(122, 8)
(122, 8)
(122, 8, 1)

         FFNN ARIMA LSTM length   kurtosis   energy    variance
Serie 1    -1    -1   -1    144  -0.273837  40.0153   0.0202794
Serie 2    -1    -1   -1    144  -0.985248  42.3551   0.0404594
Serie 3    -1    -1   -1    144   0.376218  19.6802   0.0500962
Serie 4    -1    -1   -1    133  -0.509588  43.3743   0.0350017
Serie 5    -1    -1   -1    144  -0.130784  44.9355   0.0263454
Serie 6    -1    -1   -1    144  0.0200759  35.7542   0.0233401
Serie 7    -1    -1   -1    144  -0.247972  35.5276   0.0297982
Serie 8    -1    -1   -1    134     5.1031  16.1745    0.013026
Serie 9    -1    -1   -1    141    1.47885  19.9427   0.0319149
Serie 10   -1    -1   -1    144     30.417  8.56577  0.00739935
Serie 11   -1    -1   -1    144   0.340041   22.603   0.0278349
Serie 12   -1    -1   -1    144   -1.51614  47.5136   0.0802943

In [7]:
a = 1
b = 1
try:
    b = 1/0
    a = 2
    
except:
    b = 2
print (a)
print (b)

1
2